cart/urls.py
from django.urls import path

from . views import (
    cart_add, 
    cart_detail, 
    cart_remove
    
)

app_name = 'cart'

urlpatterns = [
    path('cart-detail/', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create
 
app_name = 'orders'
 
urlpatterns = [
    path('create/', order_create, name='order_create')
]

shop/urls.py
from django.contrib import admin
from django.urls import path

from shop.views import (
    product_list, 
    product_detail,
    start_page,
    
)
from shop.views import contact, about, make_callback
app_name = 'shop'

urlpatterns = [
    path('', start_page, name='start_page'),

    path('catalog/', product_list, name='product_list'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),   
    path('<str:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('make-callback/new/', make_callback, name='callback')
   
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label='Количество:', choices=PRODUCT_QUANTITY_CHOICES, initial=PRODUCT_QUANTITY_CHOICES[0], coerce=int, 
    widget=forms.Select(
        attrs={'class': 'form-control'}
        ))

    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from shop.models import Product, Category
from .cart import Cart
from .forms import CartAddProductForm



def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.GET)
    

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    else:
        cd = form.cleaned_data
        cart.add(product=product, quantity=1, update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    messages.success(request, 'Удалено')
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)


    categories = Category.objects.all()
    carts = Cart(request)

    list_categories_8=categories
    list_categories_8 = [categories[d:d+8] for d in range(0, len(list_categories_8), 8)]
    categories_navbar1=list_categories_8[0]

    categories_navbar2=[]
    categories_navbar3=[]
    categories_navbar4=[]
    if len(categories)>8:
        categories_navbar2=list_categories_8[1]
    if len(categories)>16:
        categories_navbar3=list_categories_8[1]
    if len(categories)>24:
        categories_navbar4=list_categories_8[1]

    list_categories_footer_6=categories

    list_categories_footer_6=[categories[d:d+8]
                     for d in range(0, len(list_categories_footer_6), 6)]
    categories_footer1 = list_categories_footer_6[0]

    categories_footer2=[]
    categories_footer3=[]
    categories_footer4=[]
    categories_footer5=[]


    if len(categories)>6:
        categories_footer2=list_categories_footer_6[1]
    if len(categories)>16:
        categories_footer3=list_categories_footer_6[2]
    if len(categories)>24:
        categories_footer4=list_categories_footer_6[3]
    if len(categories)>30:
        categories_footer5=list_categories_footer_6[4]


    context = {
        
        'categories': categories,
        'categories_footer1': categories_footer1,
        'categories_footer2': categories_footer2,
        'categories_footer3': categories_footer3,
        'categories_footer4': categories_footer4,
        'categories_footer5': categories_footer5,
        'categories_navbar1': categories_navbar1,
        'categories_navbar2': categories_navbar2,
        'categories_navbar3': categories_navbar3,
        'categories_navbar4': categories_navbar4,
        'cart': cart

    }
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', context)

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

{% load user_agents %}
{% if request|is_mobile %}
   
{% endif %}
{% if request|is_tablet %}
   
{% endif %}

{% if request|is_pc %}
    <br>
<br>
<br>
{% endif %}
<div class="kenne-cart-area">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        
                            <div class="table-content table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th class="kenne-product-remove">удалить</th>
                                            <th class="kenne-product-thumbnail">изображение</th>
                                            <th class="cart-product-name">Товар</th>
                                            <th class="kenne-product-price">Цена</th>
                                            <th class="kenne-product-quantity">Количество</th>
                                            <th class="kenne-product-subtotal">Всего</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                         {% for item in cart %}
                    {% with product=item.product  %}
                                        <tr>
                                            <td class="kenne-product-remove"><a href="{% url 'cart:cart_remove' product.id %}"><i class="fa fa-trash"
                                                title="Remove"></i></a></td>
                                            <td ><img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'shop/img/default.jpg' %} {% endif %}" width="300" height="200" alt="Uren's Cart Thumbnail"></td>
                                            <td class="kenne-product-name">{{product.name}}</td>
                                            <td class="kenne-product-price"><span class="amount">{{product.price}} руб.</span></td>
                                            <td class="quantity">
                                               
                                                
                                <form action="{% url 'cart:cart_add' product.id %}" method="GET" >
                                {% csrf_token %}
                                <span style="display:inline-block">    
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit"  value="Изменить" class="btn btn-outline-info"style="margin-top:10%;"> </span>
                               
                            </form>
                                                
                                            </td>
                                            <td class="product-subtotal"><span class="amount">{{ item.total_price }} руб.</span></td>
                                        </tr>
                                       {% endwith %}
                                       {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-5 ml-auto">
                                    <div class="cart-page-total">
                                        <h2>Цена</h2>
                                        <ul>
                                            
                                            <li>Всего <span>{{ cart.get_total_price }} руб.</span></li>
                                        </ul>
                                        <a href="{% url 'orders:order_create' %}">Оформить заказ</a>
                                    </div>
                                </div>
                            </div>
                        
                    </div>
                </div>
            </div>
        </div>


{% endblock %}


{% block footer %}
{% include "footer.html" with categories_footer1=categories_footer1 categories_footer2=categories_footer2 categories_footer3=categories_footer3 categories_footer4=categories_footer4 categories_footer5=categories_footer5 %}
{% endblock %}


 <!--<div class="offcanvas-minicart_wrapper" id="miniCart">
                <div class="offcanvas-menu-inner">
                    <a href="#" class="btn-close"><i class="ion-android-close"></i></a>
                    <div class="minicart-content">
                        <div class="minicart-heading">
                            <h4>Shopping Cart</h4>
                        </div>
    
          <ul class="minicart-list">
        <h2>
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        Текущий список покупок:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
        <table class="table table-dark table-hover">
            <thead>
              <tr>
                <th scope="col">Изображение</th>
                <th scope="col">Товар</th>
                <th scope="col">Кол-во</th>
                <th scope="col">Удалить</th>
                <th scope="col">Цена одного товара</th>
                <th scope="col">Цена</th>
              </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <th scope="row">
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            </th>
                            <td>{{ product.name }}</td>
                            <td>
                            <form action="{% url 'cart:cart_add' product.id %}" method="get">
                                {% csrf_token %}
                                <span style="display:inline-block">    
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Изменить" class="btn btn-outline-info"style="margin-top:10%;">
                                </span>
                            </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Удалить</a>
                            </td>
                            <td> {{ item.price }}</td>
                            <td> {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr>
                    <td><b>Суммарная стоимость</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b> {{ cart.get_total_price }}</b></td>
                </tr>
            </tbody>
          </table>
                
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "shop:start_page" %}" class="btn btn-default">Продолжить покупку</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-primary">Оформить заказ</a>
        </p>
        </div>
    </div>
</div>

-->