cart/urls.py
from django.urls import path

from . views import (
    cart_add, 
    cart_detail, 
    cart_remove
    
)

app_name = 'cart'

urlpatterns = [
    path('cart-detail/', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create
 
app_name = 'orders'
 
urlpatterns = [
    path('create/', order_create, name='order_create')
]

shop/urls.py
from django.contrib import admin
from django.urls import path

from shop.views import (
    product_list, 
    product_detail,
    start_page,
    
)
from shop.views import contact, about, make_callback
app_name = 'shop'

urlpatterns = [
    path('', start_page, name='start_page'),

    path('catalog/', product_list, name='product_list'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),   
    path('<str:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('make-callback/new/', make_callback, name='callback')
   
]

orders/models.py
from django.db import models

from shop.models import Product
# Create your models here.


class Order (models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    phone = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)  # оплачен ли заказ

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return 'Заказ {}'.format(self.id)

    def get_total_cost(self):
        # общая сумма заказа
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email',
                  'address', 'phone']

orders/views.py
from django.shortcuts import render
from django.core.mail import send_mail

from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

# Create your views here.

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        
        if form.is_valid():
            order = form.save()
            print(order)
            for item in cart:
                OrderItem.objects.create(
                    order = order,
                    product = item['product'],
                    price = item['price'],
                    quantity = item['quantity']
                )
            cart.clear()
            send_mail('Заказ Оформлен', 
            'Войдите в админ панель, что бы просмотреть новый заказ.' , 
            'wondroussquirrel@gmail.com', 
            ['alex_zender@i.ua'], fail_silently=False)
        return render(request, 'orders/order/created.html', {'order':order})
    else:
        
        form = OrderCreateForm()
        print(form)
        
    return render(request, 'orders/order/create.html', {'form':form})

orders/templates/orders/order/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

<!--

    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Форма заказа</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <input type="submit" class="btn btn-primary" value="Подтвердить заказ">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Заказ
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span> {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Общая стоимость: {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
-->
{% block content %}

<!-- Begin Kenne's Checkout Area -->
        <div class="checkout-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                       
                    </div>
                </div>

                <br>
                
                <div class="row">
                    <div class="col-lg-6 col-12">
                        <form action="." method="post">
                            <div class="checkbox-form">
                                <h3>Информация по заказу</h3>
                                <div class="row">
                                    {% csrf_token %}
                                    
                                    <div class="col-md-6">
                                        <div class="checkout-form-list">
                                            <label>Имя <span class="required">*</span></label>
                                            <input placeholder="" type="text" name="first_name" id="id_first_name">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="checkout-form-list">
                                            <label>Фамилия <span class="required">*</span></label>
                                            <input placeholder="" type="text" name="last_name" id="id_last_name">
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-6">
                                        <div class="checkout-form-list">
                                            <label>Адресс <span class="required">*</span></label>
                                            <input  type="text" name="address" id="id_address">
                                        </div>
                                    </div>
                                    
                                    
                                    
                                    <div class="col-md-6">
                                        <div class="checkout-form-list">
                                            <label>Email <span class="required">*</span></label>
                                            <input placeholder="" type="email" name="email" id="id_email">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="checkout-form-list">
                                            <label>Телефон <span class="required">*</span></label>
                                            <input type="text" name="phone" id="id_phone">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="order-button-payment">
                                        <input  value="Оформить заказ" type="submit">
                                    </div>
                                    </div>

                                    
                                
                                    
                                
                                
                                   
                                  
                                </div>
                            </div>
                        </form>
                    </div>
                    
                               
            </div>
        </div>
    </div>

        <!-- Kenne's Checkout Area End Here -->
{% endblock %}

orders/templates/orders/order/created.html
{% extends "base.html" %}

{% block content %}
<script>
var  myAddress = "{% url 'shop:start_page' %}"; // адрес страницы, на которую нужно перейти
var myTime = 0.15; // время в минутах, через которое надо перейти на другую страницу
setTimeout ('location.href =  myAddress', myTime * 60 * 1000);
</script>
<br>
<br>
 <div class="checkout-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                       
                    </div>
                </div>

                <br>
                
                <div class="row">
                    <div class="col-lg-6 col-12">
                        
                            <div class="checkbox-form">
                                <h3>Спасибо что скупляетесь у нас</h3>
                                <div class="row">
    
       
                <h3 class="page-header">
                </h3>
                <p>Ваш заказ оформлен. Номер заказа <strong>{{ order.id }}</strong>. Наши менеджеры скоро свяжуться с вами! Через 10 секунд редирект.....</p>
            </div>
        </div>
    </div>
</div>
</div>
</div>
    
{% endblock %}