cart/urls.py
from django.urls import path

from . views import (
    cart_add, 
    cart_detail, 
    cart_remove
    
)

app_name = 'cart'

urlpatterns = [
    path('cart-detail/', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from shop.views import (
    product_list, 
    product_detail,
    start_page,
    
)
from shop.views import contact, about, make_callback
app_name = 'shop'

urlpatterns = [
    path('', start_page, name='start_page'),

    path('catalog/', product_list, name='product_list'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),   
    path('<str:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<str:slug>/', product_detail, name='product_detail'),
    path('make-callback/new/', make_callback, name='callback')
   
]

shop/models.py
import os
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField('Изображение')

    class Meta:
        ordering = ('name',)
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])
    

def get_upload_path(instance, filename):
    #  задаем название файла названием slug`а продукта
    filename = instance.slug + '.' + filename.split('.')[1]  
    return os.path.join('images/', filename)


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', 
        on_delete=models.CASCADE
        )
    name = models.CharField('Название',max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = RichTextField('Описание',config_name='awesome_ckeditor')
    price = models.DecimalField("Цена",max_digits=10, decimal_places=2)
    available = models.BooleanField("Наличие",default=True)
    stock = models.PositiveIntegerField("Количество",)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField("Фото",upload_to=get_upload_path)
      
    STATUS_CHOICES = (('Лучшее', 'Лучшее'),
                    ('Скидка', 'Скидка'))
    status = models.CharField('Статус', max_length=8, choices=STATUS_CHOICES, blank=True )
    degree = models.PositiveIntegerField('Оценка (звезд)')

                    

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

class Callback(models.Model):
    name = models.CharField('Имя',max_length=100)
    phone= models.CharField("Телефон", max_length=100)
    description=models.TextField("Пожелание")
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField("Обработано?", default=False)
    class Meta:
        verbose_name='Обратная связь'
        verbose_name_plural = 'Обратная связь'
    def __str__(self):
        return self.phone


class Banner(models.Model):
    name = models.CharField("Название/титл", max_length=300)
    description = RichTextField("Описание",config_name='awesome_ckeditor')
    image = models.ImageField("Изображение")

    class Meta:
        verbose_name='Банер'
        verbose_name_plural = 'Банера'

    
class Testominal(models.Model):
    name=models.CharField("Имя Фамилия", max_length=200)
    work=models.CharField("Должность",max_length=200,blank=True)
    text = models.TextField("Текст")
    image=models.ImageField("Фото")
    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

    def __str__(self):
        return self.name
    
        

shop/forms.py
from django import forms

from .models import Callback

class CallbackForm(forms.ModelForm):

    class Meta:
        model = Callback
        fields = ('name', 'phone', 'description')

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from .models import Category, Product, Callback, Banner, Testominal
from cart.forms import CartAddProductForm
from .forms import CallbackForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect
from django.views.generic import (
    ListView,
    DetailView
)
from cart.cart import Cart

'''
class ProductListView(ListView):
    template_name = 'shop/product/list.html'
    queryset = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context
'''

def start_page(request):
    
    products = Product.objects.filter(available=True)
    baner_first = Banner.objects.all().first()
    b=len(Banner.objects.all())
    banners=Banner.objects.all()[1:b]
    t=len(Testominal.objects.all())
    testominal_first=Testominal.objects.all().first()
    testominals=Testominal.objects.all()[1:t]
    last_products = Product.objects.filter(available=True)[:8]
    categories = Category.objects.all()
    carts = Cart(request)

    categories_len=len(categories)
    

    
    list_categories_8=categories
    list_categories_8 = [categories[d:d+8] for d in range(0, len(list_categories_8), 8)]
    categories_navbar1=list_categories_8[0]

    categories_navbar2=[]
    categories_navbar3=[]
    categories_navbar4=[]
    
    if len(categories)>8:
        
        categories_navbar2=list_categories_8[1]
    if len(categories)>16:
      
        categories_navbar3=list_categories_8[1]
    if len(categories)>24:
        
        categories_navbar4=list_categories_8[1]
   
    list_categories_footer_6=categories

    list_categories_footer_6=[categories[d:d+8]
                     for d in range(0, len(list_categories_footer_6), 6)]
    categories_footer1 = list_categories_footer_6[0]

    categories_footer2=[]
    categories_footer3=[]
    categories_footer4=[]
    categories_footer5=[]


    if len(categories)>6:
        categories_footer2=list_categories_footer_6[1]
    if len(categories)>16:
        categories_footer3=list_categories_footer_6[2]
    if len(categories)>24:
        categories_footer4=list_categories_footer_6[3]
    if len(categories)>30:
        categories_footer5=list_categories_footer_6[4]
    
    

    context = {
        'banners':banners,
        'baner_first':baner_first,
        'products': products,
        'last_products': last_products,
        'categories': categories,
        'testominals': testominals,
        'testominal_first': testominal_first,
        'categories_navbar1': categories_navbar1,
        'categories_navbar2': categories_navbar2,
        'categories_navbar3': categories_navbar3,
        'categories_navbar4': categories_navbar4,
        'categories_footer1': categories_footer1,
        'categories_footer2': categories_footer2,
        'categories_footer3': categories_footer3,
        'categories_footer4': categories_footer4,
        'categories_footer5': categories_footer5


    }
    return render(request, 'start.html', context)

    
def contact(request):
   
    categories = Category.objects.all()
    carts = Cart(request)

    list_categories_8=categories
    list_categories_8 = [categories[d:d+8] for d in range(0, len(list_categories_8), 8)]
    categories_navbar1=list_categories_8[0]

    categories_navbar2=[]
    categories_navbar3=[]
    categories_navbar4=[]
    if len(categories)>8:
        categories_navbar2=list_categories_8[1]
    if len(categories)>16:
        categories_navbar3=list_categories_8[1]
    if len(categories)>24:
        categories_navbar4=list_categories_8[1]

    list_categories_footer_6=categories

    list_categories_footer_6=[categories[d:d+8]
                     for d in range(0, len(list_categories_footer_6), 6)]
    categories_footer1 = list_categories_footer_6[0]

    categories_footer2=[]
    categories_footer3=[]
    categories_footer4=[]
    categories_footer5=[]


    if len(categories)>6:
        categories_footer2=list_categories_footer_6[1]
    if len(categories)>16:
        categories_footer3=list_categories_footer_6[2]
    if len(categories)>24:
        categories_footer4=list_categories_footer_6[3]
    if len(categories)>30:
        categories_footer5=list_categories_footer_6[4]


    context = {
        
        'categories': categories,
        'categories_footer1': categories_footer1,
        'categories_footer2': categories_footer2,
        'categories_footer3': categories_footer3,
        'categories_footer4': categories_footer4,
        'categories_footer5': categories_footer5,
        'categories_navbar1': categories_navbar1,
        'categories_navbar2': categories_navbar2,
        'categories_navbar3': categories_navbar3,
        'categories_navbar4': categories_navbar4,



    }
     
    return render(request, 'contact.html', context)
        


def about(request):
    categories = Category.objects.all()
    carts = Cart(request)


    list_categories_8=categories
    list_categories_8 = [categories[d:d+8] for d in range(0, len(list_categories_8), 8)]
    categories_navbar1=list_categories_8[0]

    categories_navbar2=[]
    categories_navbar3=[]
    categories_navbar4=[]
    if len(categories)>8:
        categories_navbar2=list_categories_8[1]
    if len(categories)>16:
        categories_navbar3=list_categories_8[1]
    if len(categories)>24:
        categories_navbar4=list_categories_8[1]
    list_categories_footer_6=categories

    list_categories_footer_6=[categories[d:d+8]
                     for d in range(0, len(list_categories_footer_6), 6)]
    categories_footer1 = list_categories_footer_6[0]

    categories_footer2=[]
    categories_footer3=[]
    categories_footer4=[]
    categories_footer5=[]


    if len(categories)>6:
        categories_footer2=list_categories_footer_6[1]
    if len(categories)>16:
        categories_footer3=list_categories_footer_6[2]
    if len(categories)>24:
        categories_footer4=list_categories_footer_6[3]
    if len(categories)>30:
        categories_footer5=list_categories_footer_6[4]


    context = {
        
        'categories': categories,
        'categories_footer1': categories_footer1,
        'categories_footer2': categories_footer2,
        'categories_footer3': categories_footer3,
        'categories_footer4': categories_footer4,
        'categories_footer5': categories_footer5,
        'categories_navbar1': categories_navbar1,
        'categories_navbar2': categories_navbar2,
        'categories_navbar3': categories_navbar3,
        'categories_navbar4': categories_navbar4,


    }




    return render(request, 'about.html', context)

def product_list(request, category_slug=None, all=None, price_low=None, price_height=None, rathings_low=None, rathings_height=None):

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    categories_len=len(categories)

    if request.GET.get('price_low'):
        products=products.order_by("price")
    if request.GET.get('price_height'):
        products=products.order_by("price").reverse()
    if request.GET.get('rathins_height'):
        products=products.order_by("degree").reverse()
    if request.GET.get('rathins_low'):
        products=products.order_by("degree")

    
    list_categories_8 = categories
    list_categories_8 = [categories[d:d+8]
                     for d in range(0, len(list_categories_8), 8)]
    categories_navbar1 = list_categories_8[0]


    categories_navbar2=[]
    categories_navbar3=[]
    categories_navbar4=[]
    if len(categories)>8:
        categories_navbar2=list_categories_8[1]
    if len(categories)>16:
        categories_navbar3=list_categories_8[1]
    if len(categories)>24:
        categories_navbar4=list_categories_8[1]

    list_categories_footer_6=categories

    list_categories_footer_6=[categories[d:d+8]
                     for d in range(0, len(list_categories_footer_6), 6)]
    categories_footer1 = list_categories_footer_6[0]

    categories_footer2=[]
    categories_footer3=[]
    categories_footer4=[]
    categories_footer5=[]


    if len(categories)>6:
        categories_footer2=list_categories_footer_6[1]
    if len(categories)>16:
        categories_footer3=list_categories_footer_6[2]
    if len(categories)>24:
        categories_footer4=list_categories_footer_6[3]
    if len(categories)>30:
        categories_footer5=list_categories_footer_6[4]

    paginator = Paginator(products, 9)

    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products= paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
       products = paginator.page(paginator.num_pages) # Show 25 contacts per page
   





    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'categories_navbar1': categories_navbar1,
        'categories_navbar2': categories_navbar2,
        'categories_navbar3': categories_navbar3,
        'categories_navbar4': categories_navbar4,
        'categories_footer1': categories_footer1,
        'categories_footer2': categories_footer2,
        'categories_footer3': categories_footer3,
        'categories_footer4': categories_footer4,
        'categories_footer5': categories_footer5
    }
    return render(request, 'catalog.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)

shop/templates/about.html
{% extends "base.html" %}
{% block content %}

            <br>
            <br>

<!-- Begin Contact Main Page Area -->
 <!-- Begin Kenne's About Us Area -->
            <div class="about-us-area">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12">
                            <div class="overview-content">
                                <h2>Добро пожаловать в <span>Mostorg</span> !</h2>
                                <p class="short_desc">
                                    Торговое оборудование для магазинов: от крючка до витрин и стеллажей.
                                    Продажа торгового оборудования - главная специализация нашего интернет-магазина.
                                    Нам важно не просто помочь вам в создании удобного торгового помещения, но и сделать это с учетом современных тенденций и веяний. необходимо, чтобы магазин был удобным и привлекательным для посетителей, подталкивая их к покупке.
                                    Поэтому перед тем, как купить торговое оборудование для магазина, нужно учесть специфику товара и его выкладки, особенности помещения и другие нюансы.
                                    В этом и состоит наша задача - предоставить такое оснащение, которое позволило бы вашему бизнесу выполнять поставленные перед ним задачи.
                                </br>
                                <h3>Индивидуальный предприниматель</h3>
<p><strong> ДЖАЛИЛОВ БАХМАН ВАЛЕХ ОГЛЫ</strong></p>
<p><br />Расчётный счёт: <strong>40802810338000256672</strong><br />Банк: <strong>ПАО СБЕРБАНК</strong><br />БИК: <strong>044525225</strong><br />Кор. Cчёт: <strong>30101810400000000225</strong><br />ОГРН: <strong>321774600255702</strong><br />ИНН: <strong>771888095989</strong><br />КПП: &mdash;</p>
                                
                                </br>
                                    <h6>Вы можете оставить заявку в разделе "Контакты" и мы подберем для вас лучший вариант.</h6>
                                </p>
                                <div class="kenne-about-us_btn-area">
                                    <a class="about-us_btn" href="{% url 'shop:contact' %}">Контакты</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Kenne's About Us Area End Here -->
            <!-- Begin Kenne's Project Countdown Area -->
            <div class="project-count-area">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="single-count text-center">
                                <div class="count-icon">
                                    <span class="ion-ios-briefcase-outline"></span>
                                </div>
                                <div class="count-title">
                                    <h2 class="count">237</h2>
                                    <span>Магазинов открылись вместе с нами</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="single-count text-center">
                                <div class="count-icon">
                                    <span class="ion-ios-wineglass-outline"></span>
                                </div>
                                <div class="count-title">
                                    <h2 class="count">1000</h2>
                                    <span>единиц продукции продаем каждый месяц</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="single-count text-center">
                                <div class="count-icon">
                                    <span class="ion-ios-lightbulb-outline"></span>
                                </div>
                                <div class="count-title">
                                    <h2 class="count">5</h2>
                                    <span>лет работаем</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-6">
                            <div class="single-count text-center">
                                <div class="count-icon">
                                    <span class="ion-happy-outline"></span>
                                </div>
                                <div class="count-title">
                                    <h2 class="count">2169</h2>
                                    <span>Счастливых клиентов</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Kenne's Project Countdown Area End Here -->

        {% block footer %}
{% include "footer.html" with categories_footer1=categories_footer1 categories_footer2=categories_footer2 categories_footer3=categories_footer3 categories_footer4=categories_footer4 categories_footer5=categories_footer5 %}
{% endblock %}
{% endblock %}

shop/templates/messages.html
{% if messages %}
        {% for message in messages %}
         {% if message.tags %}  <script> alert('{{ message }}') </script> {% endif %} 

        {% endfor %}

    {% endif %}

shop/templates/new_products.html
<!-- Begin Product Area -->
{% load static %}
        <div class="product-area ">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-title">
                            <h3>Новые продукты</h3>
                            <div class="product-arrow"></div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="kenne-element-carousel product-slider slider-nav" data-slick-options='{
                        "slidesToShow": 4,
                        "slidesToScroll": 1,
                        "infinite": false,
                        "arrows": true,
                        "dots": false,
                        "spaceBetween": 30,
                        "appendArrows": ".product-arrow"
                        }' data-slick-responsive='[
                        {"breakpoint":992, "settings": {
                        "slidesToShow": 3
                        }},
                        {"breakpoint":768, "settings": {
                        "slidesToShow": 2
                        }},
                        {"breakpoint":575, "settings": {
                        "slidesToShow": 1
                        }}
                    ]'>


                            {% for item in last_products %}
                            <div class="product-item">
                                <div class="single-product">
                                    <div class="product-img">
                                        <a href="{% url 'shop:product_list' %}">
                                            <img class="primary-img" src="{{item.image.url}}" alt="Kenne's Product Image">
                                            
                                        </a>
                                        {% if item.status == 'Лучшее' %}
                                                <span class="sticker">Лучшее</span>
                                                {% endif %}

                                                {% if item.status == 'Скидка' %}

                                                 <span class="sticker-2">Скидка</span>
                                                 {% endif %}
                                        <div class="add-actions">
                                            <ul>
                                                <li><a href="{% url 'cart:cart_add' item.id %}" data-toggle="tooltip" data-placement="right" title="В корзину"><i class="ion-bag"></i></a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="product-content">
                                        <div class="product-desc_info">
                                            <h3 class="product-name">{{item.name}}</h3>
                                            <div class="price-box">
                                                <span class="new-price">{{item.price}} руб.</span>
                                                
                                            </div>
                                            <div class="rating-box">
                                                <ul>
                                                    {% if item.degree == 0 %}
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                     </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                            
                                                    </li>

                                                    {% endif %}
                                                     {% if item.degree == 1 %}
                                                    <li><i class="ion-ios-star"></i></li>
                                                     <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                     </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                            
                                                    </li>
                                                    {% endif %}
                                                   

                                                    {% if item.degree == 2 %}
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                            
                                                    </li>

                                                    {% endif %}
                                                     {% if item.degree == 3 %}
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                    </li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                            
                                                    </li>

                                                    {% endif %}

                                                     {% if item.degree == 4 %}
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>
                                                     <li><i class="ion-ios-star"></i></li>
                                                    <li class="silver-color">
                                                                <i class="ion-ios-star-outline"></i>
                                                            
                                                    </li>

                                                    {% endif %}

                                                    {% if item.degree == 5 %}
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>
                                                     <li><i class="ion-ios-star"></i></li>
                                                    <li><i class="ion-ios-star"></i></li>

                                                    {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor%}
                            

                        
        </div>
        </div>
        </div>
        </div>
    </div>

        

                
        <!-- Product Area End Here -->

shop/templates/start.html
 {% extends "base.html" %}

{% block content %}
{% include "slider.html" %}
{% include "baner.html" with category=categories  %}

 {% include "new_products.html" with last_products=last_products %}
 {% include "all_products.html" with products=products  category=category %}
 
{% include "testominals.html" with testominals=testominals testominal_first=testominal_first%}
{% include "instagram.html" %}
 {% include "footer.html" %}
 {% endblock %}